/**
 * Deterministic pseudo-random number generator.
 *
 * Every grid in GridSentinel is reproducible from a single integer seed, so a
 * scenario a user finds in the browser can be regenerated byte-identically in
 * the training pipeline. Uses mulberry32 — small, fast, good enough statistical
 * quality for simulation work, and identical in Node and the browser.
 */

export function mulberry32(seed) {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class Rng {
  constructor(seed) {
    this.seed = seed >>> 0;
    this._next = mulberry32(this.seed);
  }

  /** Uniform in [0, 1). */
  float() {
    return this._next();
  }

  /** Uniform in [lo, hi). */
  range(lo, hi) {
    return lo + this._next() * (hi - lo);
  }

  /** Integer in [lo, hi). */
  int(lo, hi) {
    return Math.floor(this.range(lo, hi));
  }

  /** Standard normal via Box–Muller. */
  normal(mean = 0, sd = 1) {
    let u = 0;
    let v = 0;
    while (u === 0) u = this._next();
    while (v === 0) v = this._next();
    return mean + sd * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }

  /** Log-normal — used for load sizes, which are heavy-tailed in real systems. */
  logNormal(mu, sigma) {
    return Math.exp(this.normal(mu, sigma));
  }

  bool(p = 0.5) {
    return this._next() < p;
  }

  pick(arr) {
    return arr[Math.floor(this._next() * arr.length)];
  }

  /** In-place Fisher–Yates. */
  shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(this._next() * (i + 1));
      const tmp = arr[i];
      arr[i] = arr[j];
      arr[j] = tmp;
    }
    return arr;
  }
}

export function clamp(x, lo, hi) {
  return x < lo ? lo : x > hi ? hi : x;
}
